import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title key="title">Brown Man Printing</title>
        <meta
          name="google-site-verification"
          content="NThBEf9tAE1YpXNZ7TI7Is41F6bp15dtPL_sSugL1I8"
        />
        <meta
          name="keywords"
          key="keywords"
          content="Printing, Windsor, Brown Man, Brownman, Windsor Printing"
        />
        <meta
          name="description"
          key="description"
          content="Welcome to Brown Man Printing"
        />
      </head>
      {/* needtofix write proper css */}
      <body style={{ margin: "0px" }}>{children}</body>
    </html>
  );
}
